# Generated by Django 4.0.4 on 2022-04-20 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_collection_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='partnerNumber',
            new_name='partner_Number',
        ),
    ]
